### PR TITLE
Fix for oneops-admin

### PR DESCRIPTION
**Pull request by gauravlall**

### CODE REVIEW

**Comment by mosabua** [comment]
That is a terrible hack and should not be merged imho. Instead we should declare a dependency between the two projects..

**Comment by gauravlall** [comment]
I don't know if there  is a good way to reflect dependency between the `ruby` and `java`  project where code itself currently looks at the specific jars in specific folder . Would have been much easier if it was all java .. . Will set up some time and can go over this.

**Comment by mosabua** [comment]
You can still declare the dependency in the ruby project and the maybe configure the copy-dependencies goal. 

https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html

That would be the cleaner solution compared to resources hack that assumes a specific project structure and the fact that the project was built in the right order.

**Comment by gauravlall** [comment]
ok let me close this and lets talk tomorrow and see whats the best we can do .. with this

**Pull request closed without merging**
